const scanButton=document.querySelector('#scan'),skipButton=document.querySelector('#skip'),photoCard=document.querySelector('#photoCard'),photoImage=document.querySelector('#photo'),empty=document.querySelector('#photoEmpty'),count=document.querySelector('#count'),rootLabel=document.querySelector('#root'),filename=document.querySelector('#filename'),locationLabel=document.querySelector('#location'),status=document.querySelector('#status'),folderButtons=[...document.querySelectorAll('.folder')];
const slotClasses=['north','northeast','east','southeast','south','southwest','west','northwest'];
const layouts={1:['south'],2:['west','east'],3:['north','southeast','southwest'],4:['north','east','south','west'],5:['north','east','southeast','southwest','west'],6:['north','northeast','east','south','southwest','west'],7:['north','northeast','east','southeast','south','southwest','west'],8:slotClasses};
let queue=[],current=null,skipped=new Set(),busy=false,drag=null,rootName='photos';
function message(t){status.textContent=t}
function renderFolders(names){const layout=layouts[Math.min(names.length,8)]||slotClasses;folderButtons.forEach((b,i)=>{const pos=layout[i];b.hidden=i>=names.length||!pos;if(b.hidden)return;b.dataset.folder=names[i];b.querySelector('span:last-child').textContent=names[i];slotClasses.forEach(c=>b.classList.remove(c));b.classList.add('folder',pos)})}
async function api(url,options){const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data}
function apply(data){rootName=data.root||'photos';rootLabel.textContent='Termux folder: '+rootName;queue=data.photos||[];queue.sort((a,b)=>{const an=(a.name||'').toLowerCase(),bn=(b.name||'').toLowerCase();if(an==='1.jpg')return -1;if(bn==='1.jpg')return 1;return 0});skipped=new Set();renderFolders((data.folders||[]).slice(0,8));showNext()}
function showNext(){photoCard.classList.remove('dragging','dropping','dropped');photoCard.style.transform='';current=queue.find(x=>!skipped.has(x.id))||null;count.textContent=current?(queue.length-skipped.size)+' to sort · '+queue.length+' found':'No pictures waiting';filename.textContent=current?current.name:'';locationLabel.textContent=current?current.location:'';skipButton.disabled=!current||busy;folderButtons.forEach(b=>b.disabled=!current||busy);if(!current){photoImage.hidden=true;photoImage.removeAttribute('src');empty.hidden=false;empty.querySelector('strong').textContent='All caught up';empty.querySelector('span').textContent='Tap Scan again to refresh the folder.';return}empty.hidden=true;photoImage.alt=current.name;if(current.previewable){photoImage.src='/api/photo?id='+encodeURIComponent(current.id)+'&t='+Date.now();photoImage.hidden=false}else{photoImage.hidden=true;empty.hidden=false;empty.querySelector('strong').textContent=current.name;empty.querySelector('span').textContent='This format may not preview in Chrome, but you can still sort it.'}}
async function scan(){if(busy)return;busy=true;scanButton.disabled=true;message('Scanning phone folders through Termux…');try{apply(await api('/api/scan',{method:'POST'}));message('Scan complete. Flick a picture toward a folder, or tap a folder.')}catch(e){message(e.message)}finally{busy=false;scanButton.disabled=false;showNext()}}
async function sortInto(folder){if(busy||!current)return;const chosen=current;busy=true;message('Moving '+chosen.name+' to '+folder+'…');try{const result=await api('/api/sort',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:chosen.id,folder})});queue=queue.filter(x=>x.id!==chosen.id);skipped.delete(chosen.id);message('Moved to '+result.movedTo+'. '+result.remaining+' remaining.')}catch(e){message(e.message)}finally{busy=false;showNext()}}
function direction(dx,dy){const angle=Math.atan2(dy,dx),card=photoCard.getBoundingClientRect(),cx=card.left+card.width/2,cy=card.top+card.height/2;let best=null,gap=Infinity;for(const b of folderButtons.filter(x=>!x.hidden)){const r=b.getBoundingClientRect(),a=Math.atan2(r.top+r.height/2-cy,r.left+r.width/2-cx),g=Math.abs(Math.atan2(Math.sin(angle-a),Math.cos(angle-a)));if(g<gap){gap=g;best=b.dataset.folder}}return best}
function highlight(f){folderButtons.forEach(b=>b.classList.toggle('active',b.dataset.folder===f))}
function folderAtPoint(x,y){const b=folderButtons.find(b=>{if(b.hidden)return false;const r=b.getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom});return b?b.dataset.folder:null}
photoImage.addEventListener('error',()=>{if(!current)return;photoImage.hidden=true;empty.hidden=false;empty.querySelector('strong').textContent=current.name;empty.querySelector('span').textContent='Preview unavailable; you can still sort this file.'});
photoCard.addEventListener('pointerdown',e=>{if(!current||busy)return;const r=photoCard.getBoundingClientRect();drag={id:e.pointerId,x:e.clientX,y:e.clientY,left:r.left,top:r.top,width:r.width,height:r.height};photoCard.setPointerCapture(e.pointerId);photoCard.classList.add('dragging')});
photoCard.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y,d=Math.hypot(dx,dy);photoCard.style.transform='translate('+(dx*.64)+'px,'+(dy*.64)+'px) rotate('+(dx*.012)+'deg)';highlight(folderAtPoint(e.clientX,e.clientY)||(d>28?direction(dx,dy):null))});
function finish(e,commit){if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y,d=Math.hypot(dx,dy),folder=commit?(folderAtPoint(e.clientX,e.clientY)||(d>45?direction(dx,dy):null)):null,start=drag;drag=null;highlight(null);if(!folder){photoCard.classList.remove('dragging');photoCard.style.transform='';return}const target=folderButtons.find(b=>b.dataset.folder===folder),r=target.getBoundingClientRect(),x=r.left+r.width/2-(start.left+start.width/2),y=r.top+r.height/2-(start.top+start.height/2);photoCard.classList.remove('dragging');photoCard.classList.add('dropping');photoCard.style.transform='translate('+x+'px,'+y+'px) scale(.72)';setTimeout(()=>sortInto(folder),180)}
photoCard.addEventListener('pointerup',e=>finish(e,true));photoCard.addEventListener('pointercancel',e=>finish(e,false));
folderButtons.forEach(b=>b.addEventListener('click',()=>sortInto(b.dataset.folder)));
skipButton.addEventListener('click',()=>{if(!current||busy)return;skipped.add(current.id);message('Skipped '+current.name+'; it stays where it is.');showNext()});
scanButton.addEventListener('click',async()=>{if(window.showDirectoryPicker){try{const dir=await window.showDirectoryPicker({mode:'readwrite'});message('Folder opened: '+dir.name+'. Termux will rescan its configured folder.');}catch(e){if(e.name!=='AbortError')message(e.message);}}await scan();});
(async()=>{try{const data=await api('/api/photos');if(data.photos&&data.photos.length)apply(data);else await scan()}catch(e){message('Termux server is not reachable: '+e.message)}})();